##
# A GitHub Action to run Tox

name: Tox

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - tox-action

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  py310:
    runs-on: ubuntu-latest
    container: python:3.10-alpine

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Tox
      run: pip install --user --upgrade tox

    - name: Run Tox
      env:
        TOXENV: py310
      run: |
        "$HOME/.local/bin/tox"

  py27:
    runs-on: ubuntu-latest
    container: python:2.7-alpine

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Tox
      run: pip install --user --upgrade tox

    - name: Run Tox
      env:
        TOXENV: py27
      run: |
        "$HOME/.local/bin/tox"

